apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterinterceptors.triggers.tekton.dev
  labels:
    app.kubernetes.io/part-of: tekton-triggers
    triggers.tekton.dev/release: v0.30.0
    version: v0.30.0
  {{- include "tekton-triggers.labels" . | nindent 4 }}
spec:
  group: triggers.tekton.dev
  names:
    categories:
    - tekton
    - tekton-triggers
    kind: ClusterInterceptor
    plural: clusterinterceptors
    shortNames:
    - ci
    singular: clusterinterceptor
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []