apiVersion: v1
kind: ConfigMap
metadata:
  name: config-leader-election-triggers-webhook
  labels:
    app.kubernetes.io/part-of: tekton-triggers
  {{- include "tekton-triggers.labels" . | nindent 4 }}
data:
  _example: {{ .Values.configLeaderElectionTriggersWebhook.Example | toYaml | indent
    1 }}