apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-triggers-controller
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: tekton-triggers
    triggers.tekton.dev/release: v0.30.0
  {{- include "tekton-triggers.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controller.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: default
      app.kubernetes.io/name: controller
      app.kubernetes.io/part-of: tekton-triggers
    {{- include "tekton-triggers.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: tekton-triggers-controller
        app.kubernetes.io/component: controller
        app.kubernetes.io/instance: default
        app.kubernetes.io/name: controller
        app.kubernetes.io/part-of: tekton-triggers
        app.kubernetes.io/version: v0.30.0
        triggers.tekton.dev/release: v0.30.0
        version: v0.30.0
      {{- include "tekton-triggers.selectorLabels" . | nindent 8 }}
      {{- include "tekton-triggers.defaultNetworkPolicy" . | nindent 8 }}
    spec:
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - args: {{- toYaml .Values.controller.tektonTriggersController.args | nindent 8 }}
        env:
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_LOGGING_NAME
          value: {{ quote .Values.controller.tektonTriggersController.env.configLoggingName
            }}
        - name: CONFIG_OBSERVABILITY_NAME
          value: {{ quote .Values.controller.tektonTriggersController.env.configObservabilityName
            }}
        - name: CONFIG_DEFAULTS_NAME
          value: {{ quote .Values.controller.tektonTriggersController.env.configDefaultsName
            }}
        - name: METRICS_DOMAIN
          value: {{ quote .Values.controller.tektonTriggersController.env.metricsDomain
            }}
        - name: METRICS_PROMETHEUS_PORT
          value: {{ quote .Values.controller.tektonTriggersController.env.metricsPrometheusPort
            }}
        - name: CONFIG_LEADERELECTION_NAME
          value: {{ quote .Values.controller.tektonTriggersController.env.configLeaderelectionName
            }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.controller.tektonTriggersController.image.repository }}:{{ .Values.controller.tektonTriggersController.image.tag
          | default .Chart.AppVersion }}
        name: tekton-triggers-controller
        resources: {}
        securityContext: {{- toYaml .Values.controller.tektonTriggersController.containerSecurityContext
          | nindent 10 }}
      serviceAccountName: tekton-triggers-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-triggers-webhook
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/part-of: tekton-triggers
    triggers.tekton.dev/release: v0.30.0
  {{- include "tekton-triggers.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.webhook.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: webhook
      app.kubernetes.io/instance: default
      app.kubernetes.io/name: webhook
      app.kubernetes.io/part-of: tekton-triggers
    {{- include "tekton-triggers.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: tekton-triggers-webhook
        app.kubernetes.io/component: webhook
        app.kubernetes.io/instance: default
        app.kubernetes.io/name: webhook
        app.kubernetes.io/part-of: tekton-triggers
        app.kubernetes.io/version: v0.30.0
        triggers.tekton.dev/release: v0.30.0
        version: v0.30.0
      {{- include "tekton-triggers.selectorLabels" . | nindent 8 }}
      {{- include "tekton-triggers.defaultNetworkPolicy" . | nindent 8 }}
    spec:
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - env:
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_LOGGING_NAME
          value: {{ quote .Values.webhook.webhook.env.configLoggingName }}
        - name: WEBHOOK_SERVICE_NAME
          value: {{ quote .Values.webhook.webhook.env.webhookServiceName }}
        - name: WEBHOOK_SECRET_NAME
          value: {{ quote .Values.webhook.webhook.env.webhookSecretName }}
        - name: METRICS_DOMAIN
          value: {{ quote .Values.webhook.webhook.env.metricsDomain }}
        - name: CONFIG_LEADERELECTION_NAME
          value: {{ quote .Values.webhook.webhook.env.configLeaderelectionName }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.webhook.webhook.image.repository }}:{{ .Values.webhook.webhook.image.tag
          | default .Chart.AppVersion }}
        name: webhook
        ports:
        - containerPort: 9000
          name: metrics
        - containerPort: 8008
          name: profiling
        - containerPort: 8443
          name: https-webhook
        resources: {}
        securityContext: {{- toYaml .Values.webhook.webhook.containerSecurityContext |
          nindent 10 }}
      serviceAccountName: tekton-triggers-webhook