apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-triggers-controller
  labels:
    app.kubernetes.io/part-of: tekton-triggers
  {{- include "tekton-triggers.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controller.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-triggers-webhook
  labels:
    app.kubernetes.io/part-of: tekton-triggers
  {{- include "tekton-triggers.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.webhook.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-triggers-core-interceptors
  labels:
    app.kubernetes.io/part-of: tekton-triggers
  {{- include "tekton-triggers.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.coreInterceptors.serviceAccount.annotations | nindent 4 }}