apiVersion: v1
kind: ConfigMap
metadata:
  name: config-spire
  labels:
    app.kubernetes.io/part-of: tekton-pipelines
  {{- include "tekton-pipelines.labels" . | nindent 4 }}
data:
  _example: {{ .Values.configSpire.Example | toYaml | indent 1 }}