apiVersion: v1
kind: ConfigMap
metadata:
  name: config-logging
  labels:
    app.kubernetes.io/part-of: tekton-pipelines
  {{- include "tekton-pipelines.labels" . | nindent 4 }}
data:
  loglevel.controller: {{ .Values.configLogging.loglevelController | quote }}
  loglevel.webhook: {{ .Values.configLogging.loglevelWebhook | quote }}
  zap-logger-config: {{ .Values.configLogging.zapLoggerConfig | toYaml | indent 1
    }}
