apiVersion: v1
kind: ConfigMap
metadata:
  name: feature-flags
  labels:
    app.kubernetes.io/part-of: tekton-pipelines
  {{- include "tekton-pipelines.labels" . | nindent 4 }}
data:
  await-sidecar-readiness: {{ .Values.featureFlags.awaitSidecarReadiness | quote
    }}
  coschedule: {{ .Values.featureFlags.coschedule | quote }}
  disable-affinity-assistant: {{ .Values.featureFlags.disableAffinityAssistant |
    quote }}
  disable-creds-init: {{ .Values.featureFlags.disableCredsInit | quote }}
  disable-inline-spec: {{ .Values.featureFlags.disableInlineSpec | quote }}
  enable-api-fields: {{ .Values.featureFlags.enableApiFields | quote }}
  enable-artifacts: {{ .Values.featureFlags.enableArtifacts | quote }}
  enable-cel-in-whenexpression: {{ .Values.featureFlags.enableCelInWhenexpression
    | quote }}
  enable-concise-resolver-syntax: {{ .Values.featureFlags.enableConciseResolverSyntax
    | quote }}
  enable-kubernetes-sidecar: {{ .Values.featureFlags.enableKubernetesSidecar | quote
    }}
  enable-param-enum: {{ .Values.featureFlags.enableParamEnum | quote }}
  enable-provenance-in-status: {{ .Values.featureFlags.enableProvenanceInStatus |
    quote }}
  enable-step-actions: {{ .Values.featureFlags.enableStepActions | quote }}
  enable-tekton-oci-bundles: {{ .Values.featureFlags.enableTektonOciBundles | quote
    }}
  enforce-nonfalsifiability: {{ .Values.featureFlags.enforceNonfalsifiability | quote
    }}
  keep-pod-on-cancel: {{ .Values.featureFlags.keepPodOnCancel | quote }}
  require-git-ssh-secret-known-hosts: {{ .Values.featureFlags.requireGitSshSecretKnownHosts
    | quote }}
  results-from: {{ .Values.featureFlags.resultsFrom | quote }}
  running-in-environment-with-injected-sidecars: {{ .Values.featureFlags.runningInEnvironmentWithInjectedSidecars
    | quote }}
  send-cloudevents-for-runs: {{ .Values.featureFlags.sendCloudeventsForRuns | quote
    }}
  set-security-context: {{ .Values.featureFlags.setSecurityContext | quote }}
  trusted-resources-verification-no-match-policy: {{ .Values.featureFlags.trustedResourcesVerificationNoMatchPolicy
    | quote }}