apiVersion: v1
kind: ConfigMap
metadata:
  name: pipelines-info
  labels:
    app.kubernetes.io/part-of: tekton-pipelines
  {{- include "tekton-pipelines.labels" . | nindent 4 }}
data:
  version: {{ .Values.pipelinesInfo.version | quote }}