apiVersion: v1
kind: Secret
metadata:
  name: modeling-api-docker-secret
  labels:
  {{- include "modeling-api.labels" . | nindent 4 }}
data:
  .dockerconfigjson: {{ required "modelingApiDockerSecret.dockerconfigjson is required"
    .Values.modelingApiDockerSecret.dockerconfigjson | quote }}
type: kubernetes.io/dockerconfigjson

apiVersion: v1
kind: Secret
metadata:
  name: modeling-api-docker-secret
  labels:
  {{- include "modeling-api.labels" . | nindent 4 }}
type: Opaque
data:
  githubtoken: Z2hwX2dpTnFBdWdUU2Q2NkRVc3VjSmFlV0VDTVR6cm1NeDJjQlBBaw==