apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-sa
  labels:
  {{- include "modeling-api.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.tektonSa.serviceAccount.annotations | nindent 4 }}