apiVersion: v1
kind: ConfigMap
metadata:
  name: config-leader-election-triggers-controller
  labels:
    app.kubernetes.io/part-of: tekton-triggers
  {{- include "tekton-triggers.labels" . | nindent 4 }}
data:
  _example: {{ .Values.configLeaderElectionTriggersController.Example | toYaml |
    indent 1 }}