apiVersion: v1
kind: Secret
metadata:
  name: triggers-webhook-certs
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/part-of: tekton-triggers
    triggers.tekton.dev/release: v0.30.0
  {{- include "tekton-triggers.labels" . | nindent 4 }}