apiVersion: v1
kind: Secret
metadata:
  name: tekton-triggers-core-interceptors-certs
  labels:
    app.kubernetes.io/component: interceptors
    app.kubernetes.io/part-of: tekton-triggers
    triggers.tekton.dev/release: v0.30.0
  {{- include "tekton-interceptors.labels" . | nindent 4 }}