apiVersion: v1
kind: ConfigMap
metadata:
  name: bundleresolver-config
  labels:
    app.kubernetes.io/component: resolvers
    app.kubernetes.io/part-of: tekton-pipelines
  {{- include "tekton-pipelines.labels" . | nindent 4 }}
data:
  default-kind: {{ .Values.bundleresolverConfig.defaultKind | quote }}
  default-service-account: {{ .Values.bundleresolverConfig.defaultServiceAccount
    | quote }}