apiVersion: v1
kind: ConfigMap
metadata:
  name: git-resolver-config
  labels:
    app.kubernetes.io/component: resolvers
    app.kubernetes.io/part-of: tekton-pipelines
  {{- include "tekton-pipelines.labels" . | nindent 4 }}
data:
  api-token-secret-key: {{ .Values.gitResolverConfig.apiTokenSecretKey | quote }}
  api-token-secret-name: {{ .Values.gitResolverConfig.apiTokenSecretName | quote
    }}
  api-token-secret-namespace: {{ .Values.gitResolverConfig.apiTokenSecretNamespace
    | quote }}
  default-org: {{ .Values.gitResolverConfig.defaultOrg | quote }}
  default-revision: {{ .Values.gitResolverConfig.defaultRevision | quote }}
  default-url: {{ .Values.gitResolverConfig.defaultUrl | quote }}
  fetch-timeout: {{ .Values.gitResolverConfig.fetchTimeout | quote }}
  scm-type: {{ .Values.gitResolverConfig.scmType | quote }}
  server-url: {{ .Values.gitResolverConfig.serverUrl | quote }}