apiVersion: v1
kind: ConfigMap
metadata:
  name: hubresolver-config
  labels:
    app.kubernetes.io/component: resolvers
    app.kubernetes.io/part-of: tekton-pipelines
  {{- include "tekton-pipelines.labels" . | nindent 4 }}
data:
  default-artifact-hub-pipeline-catalog: {{ .Values.hubresolverConfig.defaultArtifactHubPipelineCatalog
    | quote }}
  default-artifact-hub-task-catalog: {{ .Values.hubresolverConfig.defaultArtifactHubTaskCatalog
    | quote }}
  default-kind: {{ .Values.hubresolverConfig.defaultKind | quote }}
  default-tekton-hub-catalog: {{ .Values.hubresolverConfig.defaultTektonHubCatalog
    | quote }}
  default-type: {{ .Values.hubresolverConfig.defaultType | quote }}