apiVersion: v1
kind: ConfigMap
metadata:
  name: http-resolver-config
  labels:
    app.kubernetes.io/component: resolvers
    app.kubernetes.io/part-of: tekton-pipelines
  {{- include "tekton-pipelines.labels" . | nindent 4 }}
data:
  fetch-timeout: {{ .Values.httpResolverConfig.fetchTimeout | quote }}