apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "tekton-pipelines.fullname" . }}-tekton-aggregate-view
  labels:
    app.kubernetes.io/part-of: tekton-pipelines
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  {{- include "tekton-pipelines.labels" . | nindent 4 }}
rules:
- apiGroups:
  - tekton.dev
  resources:
  - tasks
  - taskruns
  - pipelines
  - pipelineruns
  - runs
  - customruns
  - stepactions
  verbs:
  - get
  - list
  - watch