apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: modeling-api-github-listener
  labels:
  {{- include "modeling-api-deployment.labels" . | nindent 4 }}
spec:
  resources:
    kubernetesResource:
      spec:
        template:
          metadata:
            labels:
              networking/traffic-allowed: "yes"
          spec:
            {{- with .Values.tolerations }}
            tolerations:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- with .Values.nodeSelector }}
            nodeSelector:
              {{- toYaml . | nindent 14 }}
            {{- end }}
  serviceAccountName: tekton-sa
  triggers:
  - bindings:
    - ref: modeling-api-trigger-binding
    interceptors:
    - params:
      - name: secretRef
        value:
          secretKey: secretToken
          secretName: modeling-api-webhook-secret
      - name: eventTypes
        value:
        - registry_package
      ref:
        apiVersion: triggers.tekton.dev
        kind: ClusterInterceptor
        name: github
    name: modeling-api-trigger
    template:
      ref: modeling-api-trigger-template