apiVersion: v1
kind: Secret
metadata:
  name: modeling-api-github-secret
  labels:
  {{- include "modeling-api-deployment.labels" . | nindent 4 }}
stringData:
  secretToken: {{ required "modelingApiGithubSecret.secretToken is required" .Values.modelingApiGithubSecret.secretToken | quote }}
type: Opaque