apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: modeling-api-trigger-template
  labels:
  {{- include "modeling-api-deployment.labels" . | nindent 4 }}
spec:
  params:
  - name: registry_url
  - name: chart_name
  - name: chart_version
  - name: namespace
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: modeling-api-pipeline-run-
      namespace: barni-tenant
    spec:
      params:
      - name: action
        value: $(tt.body.action)
      - name: registry_url
        value: $(tt.params.registry_url)
      - name: chart_name
        value: $(tt.params.chart_name)
      - name: chart_version
        value: $(tt.params.chart_version)
      - name: namespace
        value: $(tt.params.namespace)
      pipelineRef:
        name: modeling-api-pipeline
      serviceAccountName: tekton-sa
      podTemplate:
        {{- with .Values.tolerations }}
        tolerations:
            {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.nodeSelector }}
        nodeSelector:
            {{- toYaml . | nindent 10 }}
        {{- end }}
