apiVersion: v1
kind: Secret
metadata:
  name: modeling-api-github-token
  labels:
  {{- include "modeling-api-deployment.labels" . | nindent 4 }}
stringData:
  githubtoken: {{ required "modelingApiGithubToken.githubtoken is required" .Values.modelingApiGithubToken.githubtoken | quote }}
type: Opaque