apiVersion: v1
kind: Secret
metadata:
  name: modeling-api-webhook-secret
  labels:
  {{- include "modeling-api-deployment.labels" . | nindent 4 }}
stringData:
  secretToken: {{ required "modelingApiGithubWebhookSecret.secretToken is required" .Values.modelingApiGithubWebhookSecret.secretToken | quote }}
type: Opaque