apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-role-binding-k8s
  labels:
  {{- include "modeling-api-deployment.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-role-k8s
subjects:
- kind: ServiceAccount
  name: tekton-sa
  namespace: '{{ .Release.Namespace }}'