apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-role
  labels:
  {{- include "modeling-api-deployment.labels" . | nindent 4 }}
rules:
- apiGroups:
  - triggers.tekton.dev
  resources:
  - triggers
  - interceptors
  - eventlisteners
  - triggerbindings
  - triggertemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tekton.dev
  resources:
  - pipelines
  - pipelineruns
  - tasks
  - taskruns
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-rolebinding
  labels:
  {{- include "modeling-api-deployment.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-role
subjects:
- kind: ServiceAccount
  name: tekton-sa
  namespace: '{{ .Release.Namespace }}'